<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE predictions
[
  <!ELEMENT predictions (prediction*)>
  <!ATTLIST predictions version CDATA "3.7.10">
  <!ATTLIST predictions name CDATA #REQUIRED>

  <!ELEMENT prediction ((actual_label,predicted_label,error,(prediction|distribution),attributes?)|(actual_value,predicted_value,error,attributes?))>
  <!ATTLIST prediction index CDATA #REQUIRED>

  <!ELEMENT actual_label ANY>
  <!ATTLIST actual_label index CDATA #REQUIRED>
  <!ELEMENT predicted_label ANY>
  <!ATTLIST predicted_label index CDATA #REQUIRED>
  <!ELEMENT error ANY>
  <!ELEMENT prediction ANY>
  <!ELEMENT distribution (class_label+)>
  <!ELEMENT class_label ANY>
  <!ATTLIST class_label index CDATA #REQUIRED>
  <!ATTLIST class_label predicted (yes|no) "no">
  <!ELEMENT actual_value ANY>
  <!ELEMENT predicted_value ANY>
  <!ELEMENT attributes (attribute+)>
  <!ELEMENT attribute ANY>
  <!ATTLIST attribute index CDATA #REQUIRED>
  <!ATTLIST attribute name CDATA #REQUIRED>
  <!ATTLIST attribute type (numeric|date|nominal|string|relational) #REQUIRED>
]
>

<predictions version="3.7.10" name="Glass">
  <prediction index="1">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.01</class_label>
      <class_label index="7" predicted="yes">0.986</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7" predicted="yes">0.993</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.774</class_label>
      <class_label index="2">0.101</class_label>
      <class_label index="3">0.094</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0.023</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="3">vehic wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.272</class_label>
      <class_label index="2">0.148</class_label>
      <class_label index="3" predicted="yes">0.403</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.137</class_label>
      <class_label index="7">0.036</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.957</class_label>
      <class_label index="2">0.002</class_label>
      <class_label index="3">0.038</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.789</class_label>
      <class_label index="2">0.002</class_label>
      <class_label index="3">0.199</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.009</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.941</class_label>
      <class_label index="2">0.031</class_label>
      <class_label index="3">0.026</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.001</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.237</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7" predicted="yes">0.761</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.939</class_label>
      <class_label index="2">0.011</class_label>
      <class_label index="3">0.046</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.003</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.215</class_label>
      <class_label index="2" predicted="yes">0.755</class_label>
      <class_label index="3">0.026</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.055</class_label>
      <class_label index="2" predicted="yes">0.9</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.043</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.047</class_label>
      <class_label index="2" predicted="yes">0.667</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0.277</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.065</class_label>
      <class_label index="2">0.032</class_label>
      <class_label index="3">0.087</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6" predicted="yes">0.781</class_label>
      <class_label index="7">0.032</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.017</class_label>
      <class_label index="2" predicted="yes">0.952</class_label>
      <class_label index="3">0.025</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.003</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.041</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5" predicted="yes">0.953</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.129</class_label>
      <class_label index="3">0.011</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.009</class_label>
      <class_label index="7" predicted="yes">0.85</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.003</class_label>
      <class_label index="6">0.016</class_label>
      <class_label index="7" predicted="yes">0.975</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.566</class_label>
      <class_label index="2">0.431</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.889</class_label>
      <class_label index="2">0.104</class_label>
      <class_label index="3">0.002</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.861</class_label>
      <class_label index="2">0.047</class_label>
      <class_label index="3">0.089</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.903</class_label>
      <class_label index="2">0.007</class_label>
      <class_label index="3">0.09</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.899</class_label>
      <class_label index="2">0.069</class_label>
      <class_label index="3">0.028</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.02</class_label>
      <class_label index="2" predicted="yes">0.965</class_label>
      <class_label index="3">0.008</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.522</class_label>
      <class_label index="2">0.457</class_label>
      <class_label index="3">0.018</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.841</class_label>
      <class_label index="2">0.132</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.008</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.012</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.002</class_label>
      <class_label index="2" predicted="yes">0.979</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.004</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.007</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.066</class_label>
      <class_label index="2" predicted="yes">0.93</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.846</class_label>
      <class_label index="2">0.102</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.042</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.91</class_label>
      <class_label index="2">0.005</class_label>
      <class_label index="3">0.084</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.691</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.305</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.011</class_label>
      <class_label index="3">0.013</class_label>
      <class_label index="4">0.013</class_label>
      <class_label index="5">0.018</class_label>
      <class_label index="6" predicted="yes">0.669</class_label>
      <class_label index="7">0.276</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.005</class_label>
      <class_label index="2">0.032</class_label>
      <class_label index="3">0.002</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5" predicted="yes">0.941</class_label>
      <class_label index="6">0.017</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.696</class_label>
      <class_label index="2">0.168</class_label>
      <class_label index="3">0.13</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.063</class_label>
      <class_label index="2" predicted="yes">0.834</class_label>
      <class_label index="3">0.101</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.377</class_label>
      <class_label index="2" predicted="yes">0.57</class_label>
      <class_label index="3">0.051</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.71</class_label>
      <class_label index="2">0.063</class_label>
      <class_label index="3">0.204</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.016</class_label>
      <class_label index="7">0.005</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.511</class_label>
      <class_label index="2">0.413</class_label>
      <class_label index="3">0.073</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.055</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.042</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.371</class_label>
      <class_label index="6" predicted="yes">0.527</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.025</class_label>
      <class_label index="2" predicted="yes">0.898</class_label>
      <class_label index="3">0.073</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="3">vehic wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.062</class_label>
      <class_label index="2">0.212</class_label>
      <class_label index="3" predicted="yes">0.479</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.134</class_label>
      <class_label index="7">0.109</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.056</class_label>
      <class_label index="2" predicted="yes">0.89</class_label>
      <class_label index="3">0.052</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.389</class_label>
      <class_label index="2" predicted="yes">0.567</class_label>
      <class_label index="3">0.043</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.001</class_label>
      <class_label index="2">0.061</class_label>
      <class_label index="3">0.036</class_label>
      <class_label index="4">0.017</class_label>
      <class_label index="5">0.012</class_label>
      <class_label index="6" predicted="yes">0.852</class_label>
      <class_label index="7">0.021</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.392</class_label>
      <class_label index="2" predicted="yes">0.567</class_label>
      <class_label index="3">0.039</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.195</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5" predicted="yes">0.741</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.063</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.011</class_label>
      <class_label index="5">0.051</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7" predicted="yes">0.937</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7" predicted="yes">0.994</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.091</class_label>
      <class_label index="2" predicted="yes">0.889</class_label>
      <class_label index="3">0.019</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.555</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.438</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0.005</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.694</class_label>
      <class_label index="2">0.004</class_label>
      <class_label index="3">0.302</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>