<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE predictions
[
  <!ELEMENT predictions (prediction*)>
  <!ATTLIST predictions version CDATA "3.7.10">
  <!ATTLIST predictions name CDATA #REQUIRED>

  <!ELEMENT prediction ((actual_label,predicted_label,error,(prediction|distribution),attributes?)|(actual_value,predicted_value,error,attributes?))>
  <!ATTLIST prediction index CDATA #REQUIRED>

  <!ELEMENT actual_label ANY>
  <!ATTLIST actual_label index CDATA #REQUIRED>
  <!ELEMENT predicted_label ANY>
  <!ATTLIST predicted_label index CDATA #REQUIRED>
  <!ELEMENT error ANY>
  <!ELEMENT prediction ANY>
  <!ELEMENT distribution (class_label+)>
  <!ELEMENT class_label ANY>
  <!ATTLIST class_label index CDATA #REQUIRED>
  <!ATTLIST class_label predicted (yes|no) "no">
  <!ELEMENT actual_value ANY>
  <!ELEMENT predicted_value ANY>
  <!ELEMENT attributes (attribute+)>
  <!ELEMENT attribute ANY>
  <!ATTLIST attribute index CDATA #REQUIRED>
  <!ATTLIST attribute name CDATA #REQUIRED>
  <!ATTLIST attribute type (numeric|date|nominal|string|relational) #REQUIRED>
]
>

<predictions version="3.7.10" name="Glass">
  <prediction index="1">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.017</class_label>
      <class_label index="2" predicted="yes">0.739</class_label>
      <class_label index="3">0.055</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.181</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.033</class_label>
      <class_label index="3">0.006</class_label>
      <class_label index="4">0.013</class_label>
      <class_label index="5">0.013</class_label>
      <class_label index="6" predicted="yes">0.911</class_label>
      <class_label index="7">0.024</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.976</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.023</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.816</class_label>
      <class_label index="2">0.169</class_label>
      <class_label index="3">0.014</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.942</class_label>
      <class_label index="2">0.037</class_label>
      <class_label index="3">0.02</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.787</class_label>
      <class_label index="2">0.206</class_label>
      <class_label index="3">0.007</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.003</class_label>
      <class_label index="2" predicted="yes">0.907</class_label>
      <class_label index="3">0.087</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.607</class_label>
      <class_label index="2">0.374</class_label>
      <class_label index="3">0.019</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.986</class_label>
      <class_label index="2">0.003</class_label>
      <class_label index="3">0.011</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.747</class_label>
      <class_label index="2">0.139</class_label>
      <class_label index="3">0.108</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.841</class_label>
      <class_label index="2">0.015</class_label>
      <class_label index="3">0.131</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.011</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.844</class_label>
      <class_label index="2">0.028</class_label>
      <class_label index="3">0.118</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.09</class_label>
      <class_label index="2" predicted="yes">0.805</class_label>
      <class_label index="3">0.105</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.004</class_label>
      <class_label index="2" predicted="yes">0.972</class_label>
      <class_label index="3">0.024</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.877</class_label>
      <class_label index="2">0.026</class_label>
      <class_label index="3">0.089</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.007</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="16">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.756</class_label>
      <class_label index="2">0.008</class_label>
      <class_label index="3">0.215</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.02</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="17">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.006</class_label>
      <class_label index="2" predicted="yes">0.932</class_label>
      <class_label index="3">0.06</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="18">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.805</class_label>
      <class_label index="2">0.015</class_label>
      <class_label index="3">0.169</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.01</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="19">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.419</class_label>
      <class_label index="2" predicted="yes">0.453</class_label>
      <class_label index="3">0.117</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.006</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="20">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.861</class_label>
      <class_label index="2">0.019</class_label>
      <class_label index="3">0.11</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.009</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="21">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.411</class_label>
      <class_label index="2" predicted="yes">0.583</class_label>
      <class_label index="3">0.005</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="22">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.025</class_label>
      <class_label index="2" predicted="yes">0.873</class_label>
      <class_label index="3">0.101</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="23">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.039</class_label>
      <class_label index="2" predicted="yes">0.935</class_label>
      <class_label index="3">0.025</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="24">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.042</class_label>
      <class_label index="2" predicted="yes">0.869</class_label>
      <class_label index="3">0.089</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="25">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.001</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.02</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7" predicted="yes">0.977</class_label>
    </distribution>
  </prediction>
  <prediction index="26">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.996</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="27">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.144</class_label>
      <class_label index="2" predicted="yes">0.842</class_label>
      <class_label index="3">0.012</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="28">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.008</class_label>
      <class_label index="2" predicted="yes">0.901</class_label>
      <class_label index="3">0.09</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="29">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.094</class_label>
      <class_label index="2" predicted="yes">0.796</class_label>
      <class_label index="3">0.006</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.096</class_label>
      <class_label index="6">0.005</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="30">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.013</class_label>
      <class_label index="2" predicted="yes">0.894</class_label>
      <class_label index="3">0.093</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="31">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.023</class_label>
      <class_label index="2" predicted="yes">0.844</class_label>
      <class_label index="3">0.133</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="32">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.013</class_label>
      <class_label index="2" predicted="yes">0.891</class_label>
      <class_label index="3">0.094</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="33">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.021</class_label>
      <class_label index="2" predicted="yes">0.933</class_label>
      <class_label index="3">0.045</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="34">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.504</class_label>
      <class_label index="2">0.472</class_label>
      <class_label index="3">0.024</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="35">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.663</class_label>
      <class_label index="2">0.317</class_label>
      <class_label index="3">0.019</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="36">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.072</class_label>
      <class_label index="6">0.022</class_label>
      <class_label index="7" predicted="yes">0.9</class_label>
    </distribution>
  </prediction>
  <prediction index="37">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.001</class_label>
      <class_label index="3">0.008</class_label>
      <class_label index="4">0.01</class_label>
      <class_label index="5">0.004</class_label>
      <class_label index="6" predicted="yes">0.58</class_label>
      <class_label index="7">0.397</class_label>
    </distribution>
  </prediction>
  <prediction index="38">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.029</class_label>
      <class_label index="6">0.014</class_label>
      <class_label index="7" predicted="yes">0.949</class_label>
    </distribution>
  </prediction>
  <prediction index="39">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.002</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.166</class_label>
      <class_label index="6">0.02</class_label>
      <class_label index="7" predicted="yes">0.809</class_label>
    </distribution>
  </prediction>
  <prediction index="40">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0.009</class_label>
      <class_label index="6">0.014</class_label>
      <class_label index="7" predicted="yes">0.967</class_label>
    </distribution>
  </prediction>
  <prediction index="41">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0.044</class_label>
      <class_label index="6">0.092</class_label>
      <class_label index="7" predicted="yes">0.855</class_label>
    </distribution>
  </prediction>
  <prediction index="42">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.872</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.127</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="43">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.87</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.129</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.007</class_label>
      <class_label index="2">0.168</class_label>
      <class_label index="3">0.09</class_label>
      <class_label index="4">0.013</class_label>
      <class_label index="5">0.017</class_label>
      <class_label index="6" predicted="yes">0.679</class_label>
      <class_label index="7">0.027</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.001</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.021</class_label>
      <class_label index="4">0.007</class_label>
      <class_label index="5">0.01</class_label>
      <class_label index="6">0.074</class_label>
      <class_label index="7" predicted="yes">0.888</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.607</class_label>
      <class_label index="2">0.38</class_label>
      <class_label index="3">0.012</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.748</class_label>
      <class_label index="2">0.24</class_label>
      <class_label index="3">0.011</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.596</class_label>
      <class_label index="2">0.233</class_label>
      <class_label index="3">0.169</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.78</class_label>
      <class_label index="2">0.111</class_label>
      <class_label index="3">0.105</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.003</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.763</class_label>
      <class_label index="2">0.016</class_label>
      <class_label index="3">0.214</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.002</class_label>