<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE predictions
[
  <!ELEMENT predictions (prediction*)>
  <!ATTLIST predictions version CDATA "3.7.10">
  <!ATTLIST predictions name CDATA #REQUIRED>

  <!ELEMENT prediction ((actual_label,predicted_label,error,(prediction|distribution),attributes?)|(actual_value,predicted_value,error,attributes?))>
  <!ATTLIST prediction index CDATA #REQUIRED>

  <!ELEMENT actual_label ANY>
  <!ATTLIST actual_label index CDATA #REQUIRED>
  <!ELEMENT predicted_label ANY>
  <!ATTLIST predicted_label index CDATA #REQUIRED>
  <!ELEMENT error ANY>
  <!ELEMENT prediction ANY>
  <!ELEMENT distribution (class_label+)>
  <!ELEMENT class_label ANY>
  <!ATTLIST class_label index CDATA #REQUIRED>
  <!ATTLIST class_label predicted (yes|no) "no">
  <!ELEMENT actual_value ANY>
  <!ELEMENT predicted_value ANY>
  <!ELEMENT attributes (attribute+)>
  <!ELEMENT attribute ANY>
  <!ATTLIST attribute index CDATA #REQUIRED>
  <!ATTLIST attribute name CDATA #REQUIRED>
  <!ATTLIST attribute type (numeric|date|nominal|string|relational) #REQUIRED>
]
>

<predictions version="3.7.10" name="Glass">
  <prediction index="1">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.098</class_label>
      <class_label index="2" predicted="yes">0.877</class_label>
      <class_label index="3">0.017</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.007</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.002</class_label>
      <class_label index="2" predicted="yes">0.924</class_label>
      <class_label index="3">0.065</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.006</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.016</class_label>
      <class_label index="2" predicted="yes">0.96</class_label>
      <class_label index="3">0.017</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.006</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.017</class_label>
      <class_label index="2" predicted="yes">0.968</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.012</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.591</class_label>
      <class_label index="2">0.011</class_label>
      <class_label index="3">0.366</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.025</class_label>
      <class_label index="7">0.005</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.351</class_label>
      <class_label index="2" predicted="yes">0.472</class_label>
      <class_label index="3">0.16</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.011</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.135</class_label>
      <class_label index="2" predicted="yes">0.706</class_label>
      <class_label index="3">0.15</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.009</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.809</class_label>
      <class_label index="2">0.007</class_label>
      <class_label index="3">0.174</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.498</class_label>
      <class_label index="2">0.253</class_label>
      <class_label index="3">0.234</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.008</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.001</class_label>
      <class_label index="3">0.002</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.004</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7" predicted="yes">0.988</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.88</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.119</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.018</class_label>
      <class_label index="2" predicted="yes">0.833</class_label>
      <class_label index="3">0.141</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.002</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5" predicted="yes">0.595</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.401</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.001</class_label>
      <class_label index="2" predicted="yes">0.557</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.281</class_label>
      <class_label index="6">0.159</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.196</class_label>
      <class_label index="2" predicted="yes">0.722</class_label>
      <class_label index="3">0.075</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.051</class_label>
      <class_label index="2" predicted="yes">0.828</class_label>
      <class_label index="3">0.108</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.005</class_label>
      <class_label index="7">0.003</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.555</class_label>
      <class_label index="2">0.303</class_label>
      <class_label index="3">0.139</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.114</class_label>
      <class_label index="2" predicted="yes">0.7</class_label>
      <class_label index="3">0.16</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.017</class_label>
      <class_label index="7">0.006</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.475</class_label>
      <class_label index="2">0.462</class_label>
      <class_label index="3">0.061</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.027</class_label>
      <class_label index="2" predicted="yes">0.83</class_label>
      <class_label index="3">0.134</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.014</class_label>
      <class_label index="6">0.029</class_label>
      <class_label index="7" predicted="yes">0.951</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.068</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.007</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7" predicted="yes">0.921</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.71</class_label>
      <class_label index="3">0.038</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.246</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.14</class_label>
      <class_label index="2">0.003</class_label>
      <class_label index="3">0.002</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6" predicted="yes">0.849</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.014</class_label>
      <class_label index="2" predicted="yes">0.817</class_label>
      <class_label index="3">0.168</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.016</class_label>
      <class_label index="2" predicted="yes">0.849</class_label>
      <class_label index="3">0.134</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.852</class_label>
      <class_label index="2">0.06</class_label>
      <class_label index="3">0.086</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.326</class_label>
      <class_label index="2" predicted="yes">0.637</class_label>
      <class_label index="3">0.036</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.888</class_label>
      <class_label index="2">0.101</class_label>
      <class_label index="3">0.011</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.967</class_label>
      <class_label index="2">0.015</class_label>
      <class_label index="3">0.018</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.869</class_label>
      <class_label index="2">0.115</class_label>
      <class_label index="3">0.016</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.014</class_label>
      <class_label index="7" predicted="yes">0.976</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.574</class_label>
      <class_label index="3">0.01</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.414</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.472</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5" predicted="yes">0.528</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.043</class_label>
      <class_label index="2" predicted="yes">0.607</class_label>
      <class_label index="3">0.332</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.014</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.519</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.481</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.028</class_label>
      <class_label index="2" predicted="yes">0.908</class_label>
      <class_label index="3">0.056</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.902</class_label>
      <class_label index="2">0.069</class_label>
      <class_label index="3">0.026</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.682</class_label>
      <class_label index="2">0.202</class_label>
      <class_label index="3">0.112</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.895</class_label>
      <class_label index="2">0.049</class_label>
      <class_label index="3">0.052</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.003</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.525</class_label>
      <class_label index="2">0.361</class_label>
      <class_label index="3">0.11</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.015</class_label>
      <class_label index="7" predicted="yes">0.982</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.018</class_label>
      <class_label index="7" predicted="yes">0.979</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.003</class_label>
      <class_label index="2">0.007</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5" predicted="yes">0.989</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.031</class_label>
      <class_label index="2" predicted="yes">0.814</class_label>
      <class_label index="3">0.042</class_label>
      <class_label index="4">0.011</class_label>
      <class_label index="5">0.062</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0.039</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.011</class_label>
      <class_label index="2" predicted="yes">0.942</class_label>
      <class_label index="3">0.03</class_label>
      <class_label index="4">0.006</class_label>
      <class_label index="5">0.007</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.303</class_label>
      <class_label index="2" predicted="yes">0.557</class_label>
      <class_label index="3">0.138</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.504</class_label>
      <class_label index="2">0.41</class_label>
      <class_label index="3">0.084</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.793</class_label>
      <class_label index="2">0.073</class_label>
      <class_label index="3">0.126</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.006</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.799</class_label>
      <class_label index="2">0.149</class_label>
      <class_label index="3">0.052</class_label>