<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE predictions
[
  <!ELEMENT predictions (prediction*)>
  <!ATTLIST predictions version CDATA "3.7.10">
  <!ATTLIST predictions name CDATA #REQUIRED>

  <!ELEMENT prediction ((actual_label,predicted_label,error,(prediction|distribution),attributes?)|(actual_value,predicted_value,error,attributes?))>
  <!ATTLIST prediction index CDATA #REQUIRED>

  <!ELEMENT actual_label ANY>
  <!ATTLIST actual_label index CDATA #REQUIRED>
  <!ELEMENT predicted_label ANY>
  <!ATTLIST predicted_label index CDATA #REQUIRED>
  <!ELEMENT error ANY>
  <!ELEMENT prediction ANY>
  <!ELEMENT distribution (class_label+)>
  <!ELEMENT class_label ANY>
  <!ATTLIST class_label index CDATA #REQUIRED>
  <!ATTLIST class_label predicted (yes|no) "no">
  <!ELEMENT actual_value ANY>
  <!ELEMENT predicted_value ANY>
  <!ELEMENT attributes (attribute+)>
  <!ELEMENT attribute ANY>
  <!ATTLIST attribute index CDATA #REQUIRED>
  <!ATTLIST attribute name CDATA #REQUIRED>
  <!ATTLIST attribute type (numeric|date|nominal|string|relational) #REQUIRED>
]
>

<predictions version="3.7.10" name="Glass">
  <prediction index="1">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.657</class_label>
      <class_label index="2">0.036</class_label>
      <class_label index="3">0.289</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.017</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.652</class_label>
      <class_label index="2">0.066</class_label>
      <class_label index="3">0.266</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.015</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.657</class_label>
      <class_label index="2">0.277</class_label>
      <class_label index="3">0.058</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0.004</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.845</class_label>
      <class_label index="2">0.079</class_label>
      <class_label index="3">0.072</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.6</class_label>
      <class_label index="2">0.178</class_label>
      <class_label index="3">0.213</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.033</class_label>
      <class_label index="2" predicted="yes">0.849</class_label>
      <class_label index="3">0.116</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.032</class_label>
      <class_label index="2" predicted="yes">0.88</class_label>
      <class_label index="3">0.06</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.021</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.584</class_label>
      <class_label index="3">0.048</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.016</class_label>
      <class_label index="7">0.347</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.725</class_label>
      <class_label index="2">0.269</class_label>
      <class_label index="3">0.005</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.51</class_label>
      <class_label index="2">0.227</class_label>
      <class_label index="3">0.249</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.011</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.558</class_label>
      <class_label index="2">0.405</class_label>
      <class_label index="3">0.037</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.491</class_label>
      <class_label index="2">0.387</class_label>
      <class_label index="3">0.095</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.005</class_label>
      <class_label index="7">0.019</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.034</class_label>
      <class_label index="2" predicted="yes">0.915</class_label>
      <class_label index="3">0.036</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.808</class_label>
      <class_label index="2">0.173</class_label>
      <class_label index="3">0.015</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.566</class_label>
      <class_label index="2">0.325</class_label>
      <class_label index="3">0.088</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.016</class_label>
    </distribution>
  </prediction>
  <prediction index="16">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.937</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.061</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="17">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.006</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.009</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7" predicted="yes">0.977</class_label>
    </distribution>
  </prediction>
  <prediction index="18">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.001</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.011</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7" predicted="yes">0.975</class_label>
    </distribution>
  </prediction>
  <prediction index="19">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.005</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.011</class_label>
      <class_label index="6">0.006</class_label>
      <class_label index="7" predicted="yes">0.977</class_label>
    </distribution>
  </prediction>
  <prediction index="20">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.676</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0.321</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="21">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.569</class_label>
      <class_label index="2">0.226</class_label>
      <class_label index="3">0.184</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.017</class_label>
      <class_label index="7">0.003</class_label>
    </distribution>
  </prediction>
  <prediction index="22">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.457</class_label>
      <class_label index="2">0.339</class_label>
      <class_label index="3">0.181</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.019</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.883</class_label>
      <class_label index="2">0.03</class_label>
      <class_label index="3">0.086</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.841</class_label>
      <class_label index="2">0.025</class_label>
      <class_label index="3">0.133</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.829</class_label>
      <class_label index="2">0.035</class_label>
      <class_label index="3">0.135</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.007</class_label>
      <class_label index="2" predicted="yes">0.903</class_label>
      <class_label index="3">0.086</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.727</class_label>
      <class_label index="2">0.069</class_label>
      <class_label index="3">0.202</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.22</class_label>
      <class_label index="2" predicted="yes">0.77</class_label>
      <class_label index="3">0.01</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.285</class_label>
      <class_label index="2" predicted="yes">0.707</class_label>
      <class_label index="3">0.007</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.013</class_label>
      <class_label index="2" predicted="yes">0.919</class_label>
      <class_label index="3">0.062</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.784</class_label>
      <class_label index="2">0.135</class_label>
      <class_label index="3">0.08</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.046</class_label>
      <class_label index="2" predicted="yes">0.91</class_label>
      <class_label index="3">0.037</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.544</class_label>
      <class_label index="2">0.128</class_label>
      <class_label index="3">0.327</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.164</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.003</class_label>
      <class_label index="4">0.025</class_label>
      <class_label index="5">0.041</class_label>
      <class_label index="6" predicted="yes">0.723</class_label>
      <class_label index="7">0.044</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.006</class_label>
      <class_label index="2" predicted="yes">0.909</class_label>
      <class_label index="3">0.08</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.351</class_label>
      <class_label index="2" predicted="yes">0.428</class_label>
      <class_label index="3">0.22</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.812</class_label>
      <class_label index="2">0.044</class_label>
      <class_label index="3">0.143</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="16">
    <actual_label index="6">tableware</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.007</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.038</class_label>
      <class_label index="4">0.011</class_label>
      <class_label index="5">0.004</class_label>
      <class_label index="6" predicted="yes">0.887</class_label>
      <class_label index="7">0.053</class_label>
    </distribution>
  </prediction>
  <prediction index="17">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.005</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7" predicted="yes">0.982</class_label>
    </distribution>
  </prediction>
  <prediction index="18">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.001</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.005</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.012</class_label>
      <class_label index="7" predicted="yes">0.977</class_label>
    </distribution>
  </prediction>
  <prediction index="19">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.005</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7" predicted="yes">0.982</class_label>
    </distribution>
  </prediction>
  <prediction index="20">
    <actual_label index="5">containers</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.142</class_label>
      <class_label index="2" predicted="yes">0.327</class_label>
      <class_label index="3">0.179</class_label>
      <class_label index="4">0.013</class_label>
      <class_label index="5">0.271</class_label>
      <class_label index="6">0.068</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="21">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.812</class_label>
      <class_label index="2">0.128</class_label>
      <class_label index="3">0.058</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="22">
    <actual_label index="3">'vehic wind float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.002</class_label>
      <class_label index="2" predicted="yes">0.888</class_label>
      <class_label index="3">0.106</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="1">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.485</class_label>
      <class_label index="2">0.426</class_label>
      <class_label index="3">0.085</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.625</class_label>
      <class_label index="2">0.123</class_label>
      <class_label index="3">0.234</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.016</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.906</class_label>
      <class_label index="2">0.07</class_label>
      <class_label index="3">0.022</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.826</class_label>
      <class_label index="2">0.139</class_label>
      <class_label index="3">0.032</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.469</class_label>
      <class_label index="2">0.461</class_label>
      <class_label index="3">0.064</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="1">'build wind float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1" predicted="yes">0.725</class_label>
      <class_label index="2">0.06</class_label>
      <class_label index="3">0.197</class_label>