<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE predictions
[
  <!ELEMENT predictions (prediction*)>
  <!ATTLIST predictions version CDATA "3.7.10">
  <!ATTLIST predictions name CDATA #REQUIRED>

  <!ELEMENT prediction ((actual_label,predicted_label,error,(prediction|distribution),attributes?)|(actual_value,predicted_value,error,attributes?))>
  <!ATTLIST prediction index CDATA #REQUIRED>

  <!ELEMENT actual_label ANY>
  <!ATTLIST actual_label index CDATA #REQUIRED>
  <!ELEMENT predicted_label ANY>
  <!ATTLIST predicted_label index CDATA #REQUIRED>
  <!ELEMENT error ANY>
  <!ELEMENT prediction ANY>
  <!ELEMENT distribution (class_label+)>
  <!ELEMENT class_label ANY>
  <!ATTLIST class_label index CDATA #REQUIRED>
  <!ATTLIST class_label predicted (yes|no) "no">
  <!ELEMENT actual_value ANY>
  <!ELEMENT predicted_value ANY>
  <!ELEMENT attributes (attribute+)>
  <!ELEMENT attribute ANY>
  <!ATTLIST attribute index CDATA #REQUIRED>
  <!ATTLIST attribute name CDATA #REQUIRED>
  <!ATTLIST attribute type (numeric|date|nominal|string|relational) #REQUIRED>
]
>

<predictions version="3.7.10" name="Glass">
  <prediction index="1">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.451</class_label>
      <class_label index="3">0.081</class_label>
      <class_label index="4">0.036</class_label>
      <class_label index="5">0.244</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.187</class_label>
    </distribution>
  </prediction>
  <prediction index="2">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.015</class_label>
      <class_label index="2">0.013</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5" predicted="yes">0.97</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="3">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.048</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7" predicted="yes">0.949</class_label>
    </distribution>
  </prediction>
  <prediction index="4">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.012</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.017</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7" predicted="yes">0.968</class_label>
    </distribution>
  </prediction>
  <prediction index="5">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.023</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7" predicted="yes">0.973</class_label>
    </distribution>
  </prediction>
  <prediction index="6">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.024</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7" predicted="yes">0.972</class_label>
    </distribution>
  </prediction>
  <prediction index="7">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.022</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7" predicted="yes">0.974</class_label>
    </distribution>
  </prediction>
  <prediction index="8">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0.006</class_label>
      <class_label index="3">0.001</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.018</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7" predicted="yes">0.974</class_label>
    </distribution>
  </prediction>
  <prediction index="9">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.025</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7" predicted="yes">0.971</class_label>
    </distribution>
  </prediction>
  <prediction index="10">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.026</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7" predicted="yes">0.97</class_label>
    </distribution>
  </prediction>
  <prediction index="11">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.023</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7" predicted="yes">0.972</class_label>
    </distribution>
  </prediction>
  <prediction index="12">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.012</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.007</class_label>
      <class_label index="6">0.136</class_label>
      <class_label index="7" predicted="yes">0.84</class_label>
    </distribution>
  </prediction>
  <prediction index="13">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.022</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7" predicted="yes">0.973</class_label>
    </distribution>
  </prediction>
  <prediction index="14">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.022</class_label>
      <class_label index="6">0.003</class_label>
      <class_label index="7" predicted="yes">0.974</class_label>
    </distribution>
  </prediction>
  <prediction index="15">
    <actual_label index="7">headlamps</actual_label>
    <predicted_label index="7">headlamps</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.022</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7" predicted="yes">0.975</class_label>
    </distribution>
  </prediction>
  <prediction index="16">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.07</class_label>
      <class_label index="2" predicted="yes">0.693</class_label>
      <class_label index="3">0.012</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.219</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="17">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.376</class_label>
      <class_label index="2">0.14</class_label>
      <class_label index="3">0.004</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5" predicted="yes">0.459</class_label>
      <class_label index="6">0.018</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="18">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.016</class_label>
      <class_label index="2" predicted="yes">0.823</class_label>
      <class_label index="3">0.159</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="19">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.464</class_label>
      <class_label index="2">0.374</class_label>
      <class_label index="3">0.156</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="20">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.046</class_label>
      <class_label index="2" predicted="yes">0.809</class_label>
      <class_label index="3">0.023</class_label>
      <class_label index="4">0.008</class_label>
      <class_label index="5">0.108</class_label>
      <class_label index="6">0.005</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="21">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.852</class_label>
      <class_label index="2">0.008</class_label>
      <class_label index="3">0.011</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.129</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="22">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.865</class_label>
      <class_label index="2">0.045</class_label>
      <class_label index="3">0.029</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.018</class_label>
      <class_label index="6">0.04</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="23">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.003</class_label>
      <class_label index="2" predicted="yes">0.883</class_label>
      <class_label index="3">0.04</class_label>
      <class_label index="4">0.013</class_label>
      <class_label index="5">0.058</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="24">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="5">containers</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.112</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0</class_label>
      <class_label index="5" predicted="yes">0.887</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="25">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.002</class_label>
      <class_label index="2" predicted="yes">0.852</class_label>
      <class_label index="3">0.144</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="26">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.785</class_label>
      <class_label index="2">0.115</class_label>
      <class_label index="3">0.099</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="27">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.84</class_label>
      <class_label index="2">0.066</class_label>
      <class_label index="3">0.085</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0.007</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="28">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.736</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.232</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.025</class_label>
      <class_label index="7">0.005</class_label>
    </distribution>
  </prediction>
  <prediction index="29">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.007</class_label>
      <class_label index="2" predicted="yes">0.9</class_label>
      <class_label index="3">0.047</class_label>
      <class_label index="4">0.012</class_label>
      <class_label index="5">0.031</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="30">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.522</class_label>
      <class_label index="2">0.243</class_label>
      <class_label index="3">0.233</class_label>
      <class_label index="4">0.003</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="31">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0</class_label>
      <class_label index="2" predicted="yes">0.857</class_label>
      <class_label index="3">0</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0.012</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0.129</class_label>
    </distribution>
  </prediction>
  <prediction index="32">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.929</class_label>
      <class_label index="2">0.007</class_label>
      <class_label index="3">0.04</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.022</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="33">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.055</class_label>
      <class_label index="2" predicted="yes">0.838</class_label>
      <class_label index="3">0.09</class_label>
      <class_label index="4">0.009</class_label>
      <class_label index="5">0.007</class_label>
      <class_label index="6">0.001</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="34">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.001</class_label>
      <class_label index="2" predicted="yes">0.857</class_label>
      <class_label index="3">0.14</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="35">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.019</class_label>
      <class_label index="2" predicted="yes">0.874</class_label>
      <class_label index="3">0.085</class_label>
      <class_label index="4">0.011</class_label>
      <class_label index="5">0.006</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="36">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.043</class_label>
      <class_label index="2" predicted="yes">0.811</class_label>
      <class_label index="3">0.144</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="37">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.902</class_label>
      <class_label index="2">0.013</class_label>
      <class_label index="3">0.082</class_label>
      <class_label index="4">0.002</class_label>
      <class_label index="5">0.001</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="38">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.058</class_label>
      <class_label index="2" predicted="yes">0.841</class_label>
      <class_label index="3">0.07</class_label>
      <class_label index="4">0.012</class_label>
      <class_label index="5">0.012</class_label>
      <class_label index="6">0.008</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="39">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.003</class_label>
      <class_label index="2" predicted="yes">0.852</class_label>
      <class_label index="3">0.144</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="40">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.899</class_label>
      <class_label index="2">0.017</class_label>
      <class_label index="3">0.083</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="41">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.002</class_label>
      <class_label index="2" predicted="yes">0.901</class_label>
      <class_label index="3">0.083</class_label>
      <class_label index="4">0.009</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0.004</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="42">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.052</class_label>
      <class_label index="2" predicted="yes">0.845</class_label>
      <class_label index="3">0.078</class_label>
      <class_label index="4">0.011</class_label>
      <class_label index="5">0.009</class_label>
      <class_label index="6">0.005</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="43">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="6">tableware</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1">0.146</class_label>
      <class_label index="2">0.125</class_label>
      <class_label index="3">0.006</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0.14</class_label>
      <class_label index="6" predicted="yes">0.573</class_label>
      <class_label index="7">0.006</class_label>
    </distribution>
  </prediction>
  <prediction index="44">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.028</class_label>
      <class_label index="2" predicted="yes">0.811</class_label>
      <class_label index="3">0.096</class_label>
      <class_label index="4">0.016</class_label>
      <class_label index="5">0.006</class_label>
      <class_label index="6">0.042</class_label>
      <class_label index="7">0.001</class_label>
    </distribution>
  </prediction>
  <prediction index="45">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.75</class_label>
      <class_label index="2">0.128</class_label>
      <class_label index="3">0.11</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0.007</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="46">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.796</class_label>
      <class_label index="2">0</class_label>
      <class_label index="3">0.184</class_label>
      <class_label index="4">0.001</class_label>
      <class_label index="5">0</class_label>
      <class_label index="6">0.017</class_label>
      <class_label index="7">0.002</class_label>
    </distribution>
  </prediction>
  <prediction index="47">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.794</class_label>
      <class_label index="2">0.086</class_label>
      <class_label index="3">0.11</class_label>
      <class_label index="4">0.004</class_label>
      <class_label index="5">0.006</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="48">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="1">build wind float</predicted_label>
    <error>yes</error>
    <distribution>
      <class_label index="1" predicted="yes">0.638</class_label>
      <class_label index="2">0.208</class_label>
      <class_label index="3">0.147</class_label>
      <class_label index="4">0.005</class_label>
      <class_label index="5">0.002</class_label>
      <class_label index="6">0</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="49">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.043</class_label>
      <class_label index="2" predicted="yes">0.86</class_label>
      <class_label index="3">0.071</class_label>
      <class_label index="4">0.011</class_label>
      <class_label index="5">0.013</class_label>
      <class_label index="6">0.002</class_label>
      <class_label index="7">0</class_label>
    </distribution>
  </prediction>
  <prediction index="50">
    <actual_label index="2">'build wind non-float'</actual_label>
    <predicted_label index="2">build wind non-float</predicted_label>
    <error>no</error>
    <distribution>
      <class_label index="1">0.004</class_label>
      <class_label index="2" predicted="yes">0.843</class_label>
      <class_label index="3">0.002</class_label>
      <class_label index="4">0.001</class_label>